### ISSUE TITLE
Jobs required projectId

### ISSUE THREAD

**Issue by andreaschandra** [Paperspace/Docs#38]
I follow an instruction from the docs to run a job and it throw an error Error: Missing option "--projectId".
It would be nice if the documentation add projectId in the job parameter basic.

![image](https://user-images.githubusercontent.com/13943428/86322049-6bd39000-bc64-11ea-8f52-bcf486447899.png)

Thanks

**Comment by mkulaczkowski** [comment]
Thanks @andreaschandra  - added to the docs

**Comment by NutthaponSmart** [comment]
＼（^０＾）／＼（^０＾）／
